### ISSUE TITLE
undefined reference to 'deny_new_usb' on 5.9.1 Patchset

### ISSUE THREAD

**Issue by karesmakro** [anthraxx/linux-hardened#53] opened 2020-10-17 14:12 UTC
There may be a problem with deny_new_usb on kernel 5.9.1

`ld: kernel/sysctl.o:(.data+0x21e8): undefined reference to 'deny_new_usb'
make[3]: *** [Makefile:1162: vmlinux] Fehler 1
make[2]: *** [debian/rules:6: build] Fehler 2`

**Comment by anthraxx** [comment] 2020-10-18 18:27
I assume you have some of the USB components as modules now? Either way, a solution could be found in the `wip/usb-sysctl` branch. can you test applying both commits on top, the _currently_

**Comment by karesmakro** [comment] 2020-10-20 11:41
Thank you for your response! Yes I have USB components as modules. I'v tested the branch and the build was successfull. Thank you

**Comment by anthraxx** [comment] 2020-12-22 02:08
duplicate of and fixed by #50

**Closed by anthraxx** 2020-12-22 02:08 UTC
Labels: bug
